### ISSUE TITLE
Sorting Tagged Payload

### ISSUE THREAD

**Issue by akov800** [iotaledger/inx-indexer#128]
Hello! 

I am looking forward to be able to sort the Tangle in order to get a list of all the transactions with a specific tag in the tagged payload type. Is this currently possible with the INX Indexer service - seems like it is not - and are there any future intentions on adding this functionality to the API? I've seen that there has been a feature open on a similar topic for more than a year now #4. 

Thanks you in advance!

**Comment by alexsporn** [comment]
Sorry I just saw this today. The indexer only indexes outputs, so the optional tagged payload on the transaction level is not indexed. There are no current plans to index anything at the transaction level right now.
