### ISSUE TITLE
Indexer crashing on account destruction

### ISSUE THREAD

**Issue by daria305** [iotaledger/inx-indexer#176]
When running evil-tools script for deletion of an account: [script](https://github.com/iotaledger/evil-tools/blob/main/scripts/test_account_implicit.sh) the indexer is crushing with the following error:
```
inx-indexer-1       | 2024-01-11T08:09:20Z      WARNING         /scratch/pkg/indexer/indexer.go:181 UNIQUE constraint failed: accounts.account_id
inx-indexer-1       | [0.037ms] [rows:0] INSERT INTO `accounts` (`account_id`,`output_id`,`amount`,`issuer`,`sender`,`address`,`created_at_slot`,`deleted_at_slot`,`committed`) VALUES ("<binary>","<binary>","1000000000","","","<binary>",48,0,false) 
inx-indexer-1       | 2024-01-11T08:09:20Z      ERROR           ListenToAcceptedTransactions failed: UNIQUE constraint failed: accounts.account_id 
inx-indexer-1       | 2024-01-11T08:09:20Z      INFO    Indexer Stopping AcceptedTransactions ... done 
```

The crush seems to be caused by destroying transaction: account on the input side, basic output on the output.

**Comment by muXxer** [comment]
Maybe that is linked to the recent problem of the iota-sdk team, where they reported a weird behavior during account transition.

**Comment by muXxer** [comment]
See also https://github.com/iotaledger/iota-core/issues/660#issuecomment-1898405715
